CREATE TABLE "user" (
  id UUID NOT NULL,
   username VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL,
   email VARCHAR(255),
   CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE project (
  id UUID NOT NULL,
   end_date TIMESTAMP WITHOUT TIME ZONE,
   name VARCHAR(255) NOT NULL,
   start_date TIMESTAMP WITHOUT TIME ZONE,
   manager_id UUID,
   CONSTRAINT pk_project PRIMARY KEY (id)
);


CREATE TABLE task (
  id UUID NOT NULL,
   name VARCHAR(255),
   start_date TIMESTAMP WITHOUT TIME ZONE,
   end_date TIMESTAMP WITHOUT TIME ZONE,
   assignee_id UUID,
   project_id UUID,
   CONSTRAINT pk_task PRIMARY KEY (id)
);

ALTER TABLE "user" ADD CONSTRAINT uc_user_email UNIQUE (email);

ALTER TABLE project ADD CONSTRAINT FK_PROJECT_ON_MANAGER FOREIGN KEY (manager_id) REFERENCES "user" (id);

ALTER TABLE task ADD CONSTRAINT FK_TASK_ON_ASSIGNEE FOREIGN KEY (assignee_id) REFERENCES "user" (id);

ALTER TABLE task ADD CONSTRAINT FK_TASK_ON_PROJECT FOREIGN KEY (project_id) REFERENCES project (id);